[package]
name = "cakesplitter-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "cakesplitter"
path = "src/main.rs"

[dependencies]
cakesplitter-core = { path = "../cakesplitter-core" }
cakesplitter-desktop-runtime = { path = "../cakesplitter-desktop-runtime" }
cakesplitter-format = { path = "../cakesplitter-format" }
chrono.workspace = true
clap.workspace = true
ctrlc.workspace = true
fs4.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
windows-sys.workspace = true

[dev-dependencies]
tempfile.workspace = true
